### ISSUE TITLE
bug(code-server): Inability to set object values in `settings`

### ISSUE THREAD

**Issue by phorcys420** [coder/modules#296]
[Discord Thread](https://discord.com/channels/747933592273027093/1287083320949080125)

---

The type of the [`settings` variable](https://github.com/coder/modules/blob/93c4fb3a8df4add1ca9e82897e26b6e207291c1b/code-server/main.tf#L41-L45) is `map(string)` and therefore does not allow you to set settings like [`files.exclude`](https://stackoverflow.com/a/33277809) which takes in an object.

You would want to set the value like this, but the type doesn't allow you to do so.
```
settings = {
    "files.exclude" = {
      "**/.*": true
    },
    "workbench.colorTheme" = "Default Dark Modern"
}
```

I think all that has to be done is set the variable's type to `map(any)`.

**Comment by phorcys420** [comment]
@matifali, could you take a look?
it should be a relatively low effort fix, i just won't have time to look into it for a bit

**Comment by matifali** [comment]
From https://github.com/coder/modules/issues/357#issue-2713150237

L.S.

I found the following bug. The `settings` variable of the `code-server` module is currently typed as `[map(string).](https://github.com/coder/modules/blob/675c82367a3d53be5f719fca4444fbf5b0ce22ac/code-server/main.tf#L42)` This is a bug, in my opinion, because it does now allow settings with subkeys to be used, which causes a Terraform error. After all, the value is not a string.

```json
settings = {
  "yaml.customTags": [
    "!reference sequence",
    "!vault scalar",
    "inputs sequence"
  ]
}
```

FIX: To allow vscode setting to be set correctly, the type of the variable should be `map(object)`.

Please advice.

**Comment by gjrtimmer** [comment]
It require some investigation, however as @phorcys420 noted and my analysis, the type of the `settings` variable should either be:

`map(any)` OR `map(object)` I think for now that @phorcys420 is right and it should be `map(any)`

**Comment by gjrtimmer** [comment]
So I built the module locally and figured out what the variable type has to be; it must be `any`; actually; otherwise, it will not work. It requires any because the settings json can be comprised of both key/value os of key/object, in the same json document. Therefor any kind of `map` will not work.

Type must be: `any`

@phorcys420 comments?
