### ISSUE TITLE
filebrowser icon does not work

### ISSUE THREAD

**Issue by gjrtimmer** [coder/modules#349]
The filebrowser icon does not work.

Used code:

```
module "filebrowser" {
  source        = "registry.coder.com/modules/filebrowser/coder"
  version       = "~>1.0.23"
  agent_id      = coder_agent.main.id
  agent_name    = "main"
  subdomain     = false
  folder        = "/home/coder"
  database_path = ".config/filebrowser.db"
  order         = 3
}
```

![Image](https://github.com/user-attachments/assets/11397720-8ef4-4602-a1c0-22f316e2e30a)

Is this related to that PR that updated or changed the filebrowser icon in the coder/coder repository?

**Comment by matifali** [comment]
Hi @gjrtimmer this is not an issue with module. The module icon was updated to use a builtin path in https://github.com/coder/modules/commit/f5ab7995d145971d25766ba826901b7eac4c5227
that did not exist and broke the icon display. It was fixed in https://github.com/coder/coder/commit/5a6d23a4a3a2225e3440f4a2dd83b3fc1fdffaa4 and is availble as per v2.17.0 and later versions of Coder.
