### ISSUE TITLE
Document breaking changes 

### ISSUE THREAD

**Issue by matifali** [coder/modules#55]
We should document the behavior when we update a module in such a way that it breaks existing templates. Examples are. 

1. Adding/removing/renaming required variables.
2. Updating default values of any variable.
3. etc

## Suggestions

- use versioning, so that if someone uses 
```hcl
module "jfrog" {
    source                   = "https://registry.coder.com/modules/jfrog"
	version                  = "1.0"
    agent_id                 = coder_agent.main.id
    jfrog_url                = "https://YYY.jfrog.io"
    ...
}
```
- more ideas

cc: @bpmct, @kylecarbs

**Comment by bpmct** [comment]
I'm a huge fan of versioning our modules so that our users always have to opt-in to a new module behavior. How is this possible if our modules are hosted in GitHub, and not a registry? Perhaps we will need to https://registry.coder.com a more mature registry. 

Alternatively, we could reference `source` being a specific commit SHA or tag and have separate releases for modules.

Main reasoning being: We should, of course document breaking changes, but I think a versioning system is far more important at first. Then, each module could perhaps have a changelog.

**Comment by matifali** [comment]
Closer in #122
