### ISSUE TITLE
GCP Regions/Zones Module

### ISSUE THREAD

**Issue by bpmct** [coder/modules#8]
Figuring out all of the flag emojis and friendly names for GCP regions is difficult. Let's make a module that has all of these 

- [ ] Output with local of all modules
- [x] `coder_parameter` 

## Should have

- [x] User can specify via a module variable a subset of regions they want to support `["us-east-1", "us-east-2"]`
- [ ] User can disable the parameter and just consume the local? idk why they would want this but why not

**Comment by matifali** [comment]
GCP has a vast range of available regions and zones. I am adding all regions, but should we include each zone in each region? There are some zones which do not have all machine types available.
https://cloud.google.com/compute/docs/regions-zones
Also, I will add an option so that the user can only choose a subset of regions, but still, should we add all regions in a Zone?
cc; @bpmct
